<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <PackageId>Buseon.Infrastructure.CQRS</PackageId>
        <Version>0.1.0</Version>
        <Authors>Rodrigo Lessa</Authors>
        <Company>Buseon</Company>
        <Description>CQRS abstractions and infrastructure for Buseon platform</Description>

        <PackageTags>CQRS messaging event-sourcing</PackageTags>
        <RepositoryUrl>https://github.com/rodrigolessa/buseon-infrastructure-cqrs</RepositoryUrl>

        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
        <PackageReference Include="Ulid" Version="1.4.1"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Buseon.Infrastructure\Buseon.Infrastructure.csproj"/>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Behaviors\" />
    </ItemGroup>

</Project>