<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <PackageId>Buseon.Infrastructure</PackageId>
        <Version>0.1.1</Version>
        <Authors>Rodrigo Lessa</Authors>
        <Company>Buseon</Company>
        <Description>Basic infrastructure for Buseon platform</Description>

        <PackageTags>Application provider DateTime provider</PackageTags>
        <RepositoryUrl>https://github.com/rodrigolessa/buseon-infrastructure-cqrs</RepositoryUrl>

        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation" Version="12.1.1" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
    </ItemGroup>

</Project>
